name: telebot
description: A starting point for Dart libraries or applications.
version: 0.0.0
# homepage: https://www.example.com
# author: me <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  http: ^0.12.0
  built_collection: '>=2.0.0 <5.0.0'
  built_value: '>=5.5.5 <7.0.0'

dev_dependencies:
  test: ^1.0.0
  build_runner: ^1.0.0
  built_value_generator: ^6.1.6
